blog/urls.py
from django.urls import path
from .views import post_list, post_detail, post_share, post_search
from .views import PostListView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import PostSitemap
from .feeds import CheckLatestPosts

# this defines the application namespace
app_name = 'blog'

sitemaps = {
    'posts': PostSitemap
}
post_feed = CheckLatestPosts()

urlpatterns = [
    path('', post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_with_tag'),
    # path('', PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>',
         post_detail, name='detail'),
    path('<int:post_id>/share/', post_share, name='post_share'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('feed/', post_feed, name='post_feed'),
    path('search/', post_search, name='search')
]

blog_project/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish', )

    def __str__(self):
        return self.title

    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse("blog:detail", args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created', )

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from .models import Comment
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ("name", 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField(max_length=255)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
# Create your views here.


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    tag = None
    object_list = Post.published.all()
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'posts': posts,
        'tag': tag,
    }
    return render(request, 'blog/post/list.html', context)


def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post, publish__year=year,
                             publish__month=month, publish__day=day, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(
        id=post.id).annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    context = {'post': post, 'comments': comments,
               'new_comment': new_comment, 'comment_form': comment_form, 'similar_posts': similar_posts}
    return render(request, 'blog/post/detail.html', context)


def post_share(request, post_id):
    # get a post
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            from_mail = 'admin@bikalpacodes.com'
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(
                cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n {}\'s comments: {}'.format(
                post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, from_mail, [cd['to']])
            sent = True
            # do stuffs with email
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    results = []
    form = SearchForm()
    query = None
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_query = SearchQuery(query)
            # search_vector = SearchVector(
            #     'title', weight='A') + SearchVector('body', weight='B')
            # results = Post.published.annotate(
            #     search=search_vector, rank=SearchRank(search_vector, search_query)).filter(rank__gte=0.3).order_by('-rank')
            results = Post.published.annotate(
                similarity=TrigramSimilarity('title', query)).filter(similarity__gte=0.3).order_by('-similarity')
    return render(request, 'blog/post/search.html', {'search_results': results, 'query': query, 'form': form})

blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
<html>
<head>
    <title>{%block title%} {% endblock %}</title>
    <link href={%static "css/blog.css"%} rel="stylesheet">

</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock content %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <h5><a href="{% url 'blog:post_list' %}">Go to Home</a></h5
            <p>This is my blog</p>
            <p>There are {% total_count %} posts in this blog. </p>
            <a href="{% url 'blog:post_feed' %}">Subscribe to RSS Feed</a>

        <h2>Latest Posts</h2>
        {% show_latest_posts %}

        <h2>Most Commented Posts</h2>
        {% get_most_commented_posts as popular_posts %}
        {% for post in popular_posts %}
            <p>{{post.title}} with {{post.comments_count}} comments.</p>
        {% endfor %}

        <h2><a href="{% url 'blog:search' %}">Search for a post</a></h2>
    </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}
{{post.title}}
{% endblock title %}

{% block content %}
<a href="{% url 'blog:post_list' %}">Go Back</a>
    <h2> {{post.title}} </h2>
    <p class="date">Published {{post.publish}} by {{post.author}} </p>
    {{post.body|markdown}}
    <p>
    <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>

    <h2>Similar Posts</h2>
    {% for post in similar_posts %}
        <p><a href="{{post.get_absolute_url}}">{{post.title}}</a></p>
    {% empty %}
        <p>No similar posts for this post.</p>
    {% endfor %}

    {% with comments.count as num_comments %}
        <h2>{{num_comments}} Comment{{num_comments|pluralize}}</h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
        <p class="info">
            Comment {{forloop.counter}} by {{comment.name}}
        </p>
        {{comment.body|linebreaks}}
        </div>
        {%empty%}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
        {% else %}
        <h2>Add a new comment</h2>
        <form action="" method="post">
            {{comment_form.as_p}}
            {% csrf_token %}
            <p><input type="submit" value="Add Comment"></p>
        </form>
    {% endif %}

{% endblock content %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{post.get_absolute_url}}"> {{post.title}}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{%load blog_tags%}
{% block title %}
My Blog
{% endblock title %}


{% block content %}
<h1>My Blog</h1>

{% if tag %}Posts with tag "{{tag.name}}"{% endif %}

{% for post in posts %}
    <h2>
        <a href="{{post.get_absolute_url}}"> {{post.title}} </a>
    </h2>
    <p class="tags">
    Tags: 
    {% for tag in post.tags.all  %}
    <a href="{% url "blog:post_list_with_tag" tag.slug %}">{{tag.name}}</a>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
    </p>
    <p class="date">Published {{post.publish}} by {{post.author}} </p>
    {{post.body|markdown|truncatewords_html:30}}
{% endfor %}

{% include 'pagination.html' with page=posts %}
{% endblock content %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}

{% block title %}Search
{% endblock title %}

{% block content %}
    {% if query %}Search results for "{{query}}" 
    <h3>{% with search_results.count as total_results %}Found {{total_results}} results. {% endwith %}</h3>
    {% for post in search_results %}
        <h4><a href="{{post.get_absolute_url}}">{{post.title}}</a></h4>
        {{post.body|truncatewords:5}}
    {% empty %}
        <h4>No search results found.</h4>
    {% endfor %}
    <p><a href="{% url 'blog:search' %}">Search Again</a></p>

    {% else %}
        <h1>Search for posts</h1>
        <form action="" method="get">
            {{form.as_p}}
            <input type="submit" value="Search">
        </form>
    {% endif %}

{% endblock content %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}
Share a post
{% endblock title %}Share a post

{% block content %}
{% if sent %}
<h1>{{post.title}} was sent successfully to {{form.cleaned_data.to}}.</h1>
{% else %}
<h1>Share "{{post.title}} by email."</h1>
<form action="." method="post">
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" value="Send email">
</form>
{% endif %}
{% endblock content %}

blog/templates/pagination.html
<div class="pagination">
<span class="step-links">
    {% if page.has_previous %}
        <a href="?page={{page.previous_page_number}}">Previous</a>
    {% endif %}    
    <span class="current">
        Page {{page.number}} of {{page.paginator.num_pages}}
    </span>
    {% if page.has_next %}
        <a href="?page={{page.next_page_number}}">Next</a>
    {% endif %}
</span>
</div>